import type { Metadata } from "next";
import { Geist, Geist_Mono,Comfortaa } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { getDictionary } from "@/lib/dictionary";
import { Locale, locales } from "@/lib/i18n";
import { notFound } from "next/navigation";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const comfortaa = Comfortaa({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-comfortaa",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return locales.map((locale) => ({
    locale,
  }));
}

export default async function RootLayout({
  children,
  params,
}: Props) {
  const { locale } = params;

  //if (!locales.includes(locale)) notFound();

  return (
    <html lang={locale}>
      <body className={`${comfortaa.className} antialiased`}>
        <Navbar />
        <StoreProvider>{children}</StoreProvider>
        <Footer />
      </body>
    </html>
  );
}