import type { Metadata } from "next";
import { Geist, Geist_Mono,Comfortaa } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { getDictionary } from "@/lib/dictionary";
import { Locale, locales } from "@/lib/i18n";
import { notFound } from "next/navigation";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const comfortaa = Comfortaa({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-comfortaa",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type Props={
  children: React.ReactNode;
  params: { locale: Locale }
}
export default async function RootLayout({
  children,
  params
}: Props) {

  const { locale } = await params;

  if (!locales.includes(locale)) notFound();

  const dict = await getDictionary(locale);


  return (
    <html lang="en">
      <head>
        <link
          rel="alternate"
          hrefLang="en"
          href={`https://yoursite.com/en`}
        />
        <link
          rel="alternate"
          hrefLang="ko"
          href={`https://yoursite.com/ko`}
        />
      </head>
      <body
        className={`${comfortaa.variable} antialiased`}
      >
        <Navbar/>
        <StoreProvider>{children}</StoreProvider>
        <Footer/>
      </body>
    </html>
  );
}
